CREATE TABLE case_person (
    person_id INTEGER NOT NULL,
    case_id INTEGER NOT NULL,
    cac_id SMALLINT NOT NULL,
    address_line_1 VARCHAR(200),
    address_line_2 VARCHAR(200),
    city VARCHAR(50),
    state_abbr VARCHAR(20),
    zip VARCHAR(20),
    county VARCHAR(20),
    region VARCHAR(20),
    out_of_country BOOLEAN,
    start_date DATE,
    end_date DATE,
    home_phone_number VARCHAR(200),
    cell_phone_number VARCHAR(200),
    work_phone_number VARCHAR(200),
    email_address VARCHAR(200),
    victim_status VARCHAR(20),
    age INTEGER,
    age_unit VARCHAR(20),
    school_or_employer VARCHAR(200),
    education_level_id VARCHAR(255),
    marital_status_id VARCHAR(255),
    income_level_id VARCHAR(255),
    problematic_sex BOOLEAN,
    mili_connection BOOLEAN,
    mili_type_id VARCHAR(255),
    mili_dependent_relationship VARCHAR(255),
    mili_connection_name VARCHAR(255),
    custom_field_1 VARCHAR(255),
    csf_eligible_2 BOOLEAN,
    family_transport_assistance_3 BOOLEAN,
    custom_field_4 VARCHAR(255),
    community_5 VARCHAR(255),
    case_person_custom_field_6 VARCHAR(255),
    case_person_custom_field_7 VARCHAR(255),
    case_person_custom_field_8 VARCHAR(255),
    case_person_custom_field_9 VARCHAR(255),
    custody BOOLEAN,
    relationship_id INTEGER,
    role_id INTEGER,
    same_household BOOLEAN,
    FOREIGN KEY(person_id) REFERENCES person(person_id),
    FOREIGN KEY(case_id) REFERENCES cac_case(case_id),
    FOREIGN KEY(cac_id) REFERENCES child_advocacy_center(cac_id),
    PRIMARY KEY (person_id, case_id)
);