CREATE TABLE person (
    cac_id SMALLINT NOT NULL,
    person_id INTEGER PRIMARY KEY,
    first_name VARCHAR(256),
    middle_name VARCHAR(256),
    last_name VARCHAR(256),
    suffix VARCHAR(256),
    nick_name VARCHAR(256),
    ssn VARCHAR(9),
    date_of_birth DATE,
    date_of_death DATE,
    gender VARCHAR(20),
    self_identified_gender VARCHAR(30),
    pronouns VARCHAR(20),
    race VARCHAR(256),
    religion VARCHAR(256),
    first_language VARCHAR(256),
    voca VARCHAR(512),
    special_populations VARCHAR(512),
    risk_factors VARCHAR(512),
    csec VARCHAR(512),
    material_involvement VARCHAR(512),
    special_needs VARCHAR(512),
    comments_for_people VARCHAR(512),
    prior_convictions BOOLEAN,
    convicted_against_children BOOLEAN,
    sex_offender BOOLEAN,
    sex_predator BOOLEAN,
    housing_insecurity_risk VARCHAR(256),
    developmental_age VARCHAR(256),
    date_added DATE,
    csec_involvement VARCHAR(512),
    custom_field VARCHAR(512),
    ethnicity_6 VARCHAR(256),
    bio_custom_field_7 VARCHAR(256),
    bio_custom_field_8 VARCHAR(256),
    tribe VARCHAR(256),
    FOREIGN KEY (cac_id) REFERENCES child_advocacy_center (cac_id)
);